spring:
  datasource:
    password: plataforma
    username: plataforma
    url: jdbc:postgresql://localhost:5432/transaction
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
jwt:
  secret: 8pxTH7h8yk@8#jAZjDGaHv%d%fWqUr9zR!4WTzbJ
  expiration: 19999999